n = input('Digite algo:')
print('O tipo primitivo deste valor é {}'.format(type(n)))
print(n.isspace())
print(n.isnumeric())
print(n.isalpha())
print(n.isalnum())
print(n.isupper())
print(n.islower())
print(n.istitle())
